name: single_radio
description: Single channel radio player.
publish_to: 'none'
version: 1.5.0+17

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #firebase_core: ^1.19.1
  #firebase_messaging: ^11.4.4
  #flutter_local_notifications: ^9.6.1
  #google_mobile_ads: ^1.3.0
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  http: ^0.13.4
  share_plus: ^6.3.0
  in_app_review: ^2.0.4
  flutter_markdown: ^0.6.9
  flutter_svg: ^1.1.1+1
  url_launcher: ^6.1.4
  sleek_circular_slider : ^2.0.1
  radio_player: ^1.0.1
  volume_regulator: ^2.1.0
  dart_common_utils: ^1.0.0
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  toggle_switch: ^2.0.1
  google_fonts: ^3.0.1
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.7.1+2

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.4
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0

flutter_icons:
  image_path: "assets/icons/appicon.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/icons/appicon-adaptive.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#172230"
  image: assets/images/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/text/
    - assets/svg/
    - assets/images/
    - assets/icons/
